#-----------------------------------------------------------------------
#   globals.properties : teamAgent
#-----------------------------------------------------------------------

# 서버 환경(local, dev, prod)
Globals.env = local

# 운영서버 타입(WINDOWS, UNIX)
Globals.OsType = UNIX

# DB서버 타입(mysql, oracle, altibase, tibero, cubrid, maria, postgres)
Globals.DbType = mysql

# 권한 인증방식(dummy, session, security)
Globals.Auth = dummy

# MainPage Setting
Globals.MainPage = /main.do

# 서비스URL
Globals.serviceUrl = http://localhost:8082

# Database
Globals.mysql.DriverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
Globals.mysql.Url=jdbc:log4jdbc:mysql://127.0.0.1:3306/teamagent?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
Globals.mysql.UserName = teamagent
Globals.mysql.Password = teamagent

# 로그인 인증 제한
Globals.login.Lock = true
Globals.login.LockCount = 5

# DB 설정
Globals.Master.db = teamagent
Globals.Template.db = teamagent
Globals.User.db = teamagent

Master.CompId = teamagent
Template.CompId = teamagent
User.CompId = teamagent

# 파일 업로드 경로
Globals.fileStorePath=C:/projects/team_agent/upload/
Globals.webRootPath=C:/projects/team_agent/src/main/webapp/

# 로그백업 경로
log.backupPath=D:/backupLogs/

Globals.hashedPassword=789F55D1B042EB0C02012CC8CCD501CBBA9955659621F90FB85E88585698D013
Globals.crypto.masterPath=
Globals.crypto.key=

# 파일 업로드 설정
fileUpload.defaultMaxSize = 52428800
fileUpload.defaultMaxCount = 5
fileUpload.allowFileExts = jpg,jpeg,gif,png,bmp,txt,pdf,xls,xlsx,ppt,pptx,doc,docx,hwp,zip

# 인증 설정
auth.accessCount = 5
auth.accessOtpCount = 5
auth.mainPage = redirect:/main.do
auth.otp.noAuthPage = redirect:/login.do?noOtpAuth
auth.otp.accessDeniedPage = redirect:/login.do?accessDenied
auth.otp.accessOtpFailPage = redirect:/otpLogin.do?accessOtpFail

# session timeout
globals.web.timeout = 3600000

Globals.apps=teamagent.local

# 비밀번호 초기화 전화번호
pwReset.compTel = 15443434

# 기본 테마
default.theme = blue

# 슈퍼관리자 설정
Super.CompId = super
Super.MainPgmId = PGM1221

# 권한 코드ID
Admin.AuthCodeId = 01
Super.AuthCodeGrpId = 018
Super.AuthCodeId = SUPER
