#-----------------------------------------------------------------------
#   globals.properties : teamAgent
#-----------------------------------------------------------------------

# 서버 환경(local, dev, prod)
Globals.env = prod

# 운영서버 타입(WINDOWS, UNIX)
Globals.OsType = UNIX

# DB서버 타입(mysql, oracle, altibase, tibero, cubrid, maria, postgres)
Globals.DbType = mysql

# 권한 인증방식(dummy, session, security)
Globals.Auth = dummy

# MainPage Setting
Globals.MainPage = /main.do

# 서비스URL
Globals.serviceUrl = http://localhost:8082

# Database
Globals.mysql.DriverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
Globals.mysql.Url=jdbc:log4jdbc:mysql://175.45.194.170:3306/team_agent?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
Globals.mysql.UserName = admin
Globals.mysql.Password = isparkAX12#

# 로그인 인증 제한
Globals.login.Lock = true
Globals.login.LockCount = 5

# DB 설정
Globals.Master.db = team_agent
Globals.Template.db = team_agent
Globals.User.db = team_agent

Master.CompId = team_agent
Template.CompId = team_agent
User.CompId = team_agent

# 파일 업로드 경로
Globals.fileStorePath=C:/projects/team_agent/upload/
Globals.webRootPath=C:/projects/team_agent/src/main/webapp/

# 로그백업 경로
log.backupPath=D:/backupLogs/

Globals.hashedPassword=789F55D1B042EB0C02012CC8CCD501CBBA9955659621F90FB85E88585698D013
Globals.crypto.masterPath=
Globals.crypto.key=

# 파일 업로드 설정
fileUpload.defaultMaxSize = 52428800
fileUpload.defaultMaxCount = 5
fileUpload.allowFileExts = jpg,jpeg,gif,png,bmp,txt,pdf,xls,xlsx,ppt,pptx,doc,docx,hwp,zip

# 파일 뷰 변환 설정
fileView.libreOffice.exec=/usr/bin/soffice
fileView.tempDir=/tmp
fileView.convertTimeoutSec=120
fileView.txt.maxBytes=1048576

# 인증 설정
auth.accessCount = 5
auth.accessOtpCount = 5
auth.mainPage = redirect:/main.do
auth.otp.noAuthPage = redirect:/login.do?noOtpAuth
auth.otp.accessDeniedPage = redirect:/login.do?accessDenied
auth.otp.accessOtpFailPage = redirect:/login.do?accessOtpFail

# session timeout
globals.web.timeout = 3600000

Globals.apps=teamagent.local

# 비밀번호 초기화 전화번호
pwReset.compTel = 15443434

# 기본 테마
default.theme = blue

# 슈퍼관리자 설정
Super.CompId = super
Super.MainPgmId = PGM1221

# 권한 코드ID
Admin.AuthCodeId = 01
Super.AuthCodeGrpId = 018
Super.AuthCodeId = SUPER

ncp.storage.endpoint=https://kr.object.ncloudstorage.com
ncp.storage.region=kr-standard
ncp.storage.bucket=ta-storage
ncp.storage.accessKey=4UTgxZ1WiGlKxeL2a1zq
ncp.storage.secretKey=uCux2lAQrU0zYzjZTHLWpZFWCpNqcJW0yVidfQ93

# 에이전트 API URL
Globals.chatbot.apiIp = http://61.78.123.204:

# 일반채팅 api url
Globals.chatbot.gpt.apiUrl = http://61.78.123.204:9000/query
Globals.chatbot.gpt.apiFileUrl = http://61.78.123.204:9000/file_query

# 컨텐츠관리 > 파일 저장 시 AI 다운로드 API URL
Globals.dataset.fileDownload.apiUrl = http://61.78.123.204:9111/pre_processing/download

# 데이터셋 구축 API URL
Globals.dataset.build.apiUrl = http://61.78.123.204:9111/pre_processing/run
# 데이터셋 삭제 API URL
Globals.dataset.delete.apiUrl = http://61.78.123.204:9111/pre_processing/delete
# 데이터셋 테스트 API URL
Globals.dataset.test.apiUrl = http://61.78.123.204:9111/query_test

# AI 보고서 요약/요약 생성
Globals.chatbot.summary.apiUrl = http://61.78.123.204:9000/summary_query
# AI 이미지생성
Globals.chatbot.image.apiUrl = http://61.78.123.204:9000/image_query